# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

repr_tree_cpp <- function(data, is_na, roots, yes, no, missing, is_leaf, feature, split, decision_type, trees, depth) {
    .Call(`_sylvan_repr_tree_cpp`, data, is_na, roots, yes, no, missing, is_leaf, feature, split, decision_type, trees, depth)
}

